import "server-only";
import type { ExportSectionKey, SectionedExportMode } from "@/types/export";
import type { SpecDetail } from "@/types/spec";

type TemplateContext = {
  spec: SpecDetail;
};

export type ExportTemplateDefinition = {
  mode: SectionedExportMode;
  buildTitle: (context: TemplateContext) => string;
  buildPreamble: (context: TemplateContext) => string[];
  buildFooter?: (context: TemplateContext) => string[];
  sectionTitleOverrides?: Partial<Record<ExportSectionKey, string>>;
};

export const EXPORT_TEMPLATES: Readonly<Record<SectionedExportMode, ExportTemplateDefinition>> = {
  human: {
    mode: "human",
    buildTitle: ({ spec }) => `${spec.title} - Engineering Spec`,
    buildPreamble: ({ spec }) => [
      "Generated by SpecPilot.",
      `Priority: ${spec.priority}`,
      `Status: ${spec.status}`
    ]
  },
  compact_brief: {
    mode: "compact_brief",
    buildTitle: ({ spec }) => `${spec.title} - Compact Execution Brief`,
    buildPreamble: () => ["Condensed implementation brief for quick execution handoff."]
  }
} as const;
